/**
 * Application Event Type Constants
 */

const EVENT_TYPES = {
  USER_REGISTERED: 'USER_REGISTERED',
  GAME_CREATED: 'GAME_CREATED',
  ROOM_CREATED: 'ROOM_CREATED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  GAME_STARTED: 'GAME_STARTED',
  MOVE_MADE: 'MOVE_MADE',
  GAME_WON: 'GAME_WON',
  GAME_DRAW: 'GAME_DRAW',
  GAME_COMPLETED: 'GAME_COMPLETED',
  PLAYER_LEFT: 'PLAYER_LEFT'
};

module.exports = EVENT_TYPES;
